server:
  port: 7080
spring:
  profiles:
    active: dev, swagger
  application:
    name: College
  datasource:
    #driver-class-name: org.postgresql.Driver
    password: root
    #url: jdbc:postgresql://localhost:5432/college
    username: root
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/college
    
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true


